// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gQIGZpSw45veGskq3i356Wno1UEeVeQ',
    appId: '1:827039476352:ios:8a788d8fd9541815419465',
    messagingSenderId: '827039476352',
    projectId: 'balloon-pop-19858',
    storageBucket: 'balloon-pop-19858.appspot.com',
    iosClientId: '827039476352-4br9qp813aj4o5n6r4atpmgv4icgj88n.apps.googleusercontent.com',
    iosBundleId: 'com.example.balloonPopGame',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgynIJkYwFiIM37uLzl5V3GRAcuvscSOc',
    appId: '1:827039476352:android:a628694c5bc0cdd0419465',
    messagingSenderId: '827039476352',
    projectId: 'balloon-pop-19858',
    storageBucket: 'balloon-pop-19858.appspot.com',
  );

}